# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview
    - uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore


