name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
        dotnet-quality: preview
    - uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore


